#:schema node_modules/wrangler/config-schema.json
name = "feedbackpulse"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "feedbackpulse-db"
database_id = "f8167793-0692-460f-aab0-199d1fecd574"

[[kv_namespaces]]
binding = "KV"
id = "8e514f7b52cf4e0eaf9128ffcca87b3f"

[ai]
binding = "AI"

[[workflows]]
name = "feedback-pipeline"
binding = "FEEDBACK_PIPELINE"
class_name = "FeedbackPipelineWorkflow"
